// <auto-generated />
using System;
using Disco.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Disco.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260130212027_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArtistsFollower", b =>
                {
                    b.Property<Guid>("Artistid")
                        .HasColumnType("uuid")
                        .HasColumnName("artistid");

                    b.Property<Guid>("Userid")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.HasKey("Artistid", "Userid")
                        .HasName("artists_followers_pkey");

                    b.HasIndex("Userid");

                    b.ToTable("artists_followers", (string)null);
                });

            modelBuilder.Entity("Disco.Models.Artist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Avatar")
                        .HasColumnType("text")
                        .HasColumnName("avatar");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("Deletedat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletedat");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("Updatedat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("artists_pkey");

                    b.ToTable("artists", (string)null);
                });

            modelBuilder.Entity("Disco.Models.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("Artistid")
                        .HasColumnType("uuid")
                        .HasColumnName("artistid");

                    b.Property<Guid>("Authorid")
                        .HasColumnType("uuid")
                        .HasColumnName("authorid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("Deletedat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletedat");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("Updatedat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("posts_pkey");

                    b.HasIndex(new[] { "Artistid" }, "idx_active_posts")
                        .HasFilter("(deletedat IS NULL)");

                    b.HasIndex(new[] { "Authorid" }, "idx_posts_author");

                    b.ToTable("posts", (string)null);
                });

            modelBuilder.Entity("Disco.Models.PostReaction", b =>
                {
                    b.Property<Guid>("Postid")
                        .HasColumnType("uuid")
                        .HasColumnName("postid");

                    b.Property<Guid>("Userid")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.Property<string>("Reactiontype")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("reactiontype");

                    b.HasKey("Postid", "Userid")
                        .HasName("post_reactions_pkey");

                    b.HasIndex(new[] { "Userid" }, "idx_reactions_user");

                    b.ToTable("post_reactions", (string)null);
                });

            modelBuilder.Entity("Disco.Models.RepliesReaction", b =>
                {
                    b.Property<Guid>("Replyid")
                        .HasColumnType("uuid")
                        .HasColumnName("replyid");

                    b.Property<Guid>("Userid")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.Property<string>("Reactiontype")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("reactiontype");

                    b.HasKey("Replyid", "Userid")
                        .HasName("replies_reactions_pkey");

                    b.HasIndex(new[] { "Userid" }, "idx_replies_reactions_user");

                    b.ToTable("replies_reactions", (string)null);
                });

            modelBuilder.Entity("Disco.Models.Reply", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("Authorid")
                        .HasColumnType("uuid")
                        .HasColumnName("authorid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("Deletedat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletedat");

                    b.Property<Guid?>("Parentid")
                        .HasColumnType("uuid")
                        .HasColumnName("parentid");

                    b.Property<Guid>("Postid")
                        .HasColumnType("uuid")
                        .HasColumnName("postid");

                    b.Property<DateTime?>("Updatedat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("replies_pkey");

                    b.HasIndex("Authorid");

                    b.HasIndex(new[] { "Parentid" }, "idx_replies_parent");

                    b.HasIndex(new[] { "Postid" }, "idx_replies_post");

                    b.ToTable("replies", (string)null);
                });

            modelBuilder.Entity("Disco.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Avatar")
                        .HasColumnType("text")
                        .HasColumnName("avatar");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("Deletedat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletedat");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Hashpassword")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hashpassword");

                    b.Property<bool?>("Isverified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("isverified");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Resetpasswordtoken")
                        .HasColumnType("text")
                        .HasColumnName("resetpasswordtoken");

                    b.Property<string>("Role")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role")
                        .HasDefaultValueSql("'USER'::character varying");

                    b.Property<DateTime?>("Updatedat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Verificationtoken")
                        .HasColumnType("text")
                        .HasColumnName("verificationtoken");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.HasIndex(new[] { "Email" }, "users_email_key")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("UsersFollower", b =>
                {
                    b.Property<Guid>("Followedid")
                        .HasColumnType("uuid")
                        .HasColumnName("followedid");

                    b.Property<Guid>("Followerid")
                        .HasColumnType("uuid")
                        .HasColumnName("followerid");

                    b.HasKey("Followedid", "Followerid")
                        .HasName("users_followers_pkey");

                    b.HasIndex("Followerid");

                    b.ToTable("users_followers", (string)null);
                });

            modelBuilder.Entity("ArtistsFollower", b =>
                {
                    b.HasOne("Disco.Models.Artist", null)
                        .WithMany()
                        .HasForeignKey("Artistid")
                        .IsRequired()
                        .HasConstraintName("artists_followers_artistid_fkey");

                    b.HasOne("Disco.Models.User", null)
                        .WithMany()
                        .HasForeignKey("Userid")
                        .IsRequired()
                        .HasConstraintName("artists_followers_userid_fkey");
                });

            modelBuilder.Entity("Disco.Models.Post", b =>
                {
                    b.HasOne("Disco.Models.Artist", "Artist")
                        .WithMany("Posts")
                        .HasForeignKey("Artistid")
                        .IsRequired()
                        .HasConstraintName("posts_artistid_fkey");

                    b.HasOne("Disco.Models.User", "Author")
                        .WithMany("Posts")
                        .HasForeignKey("Authorid")
                        .IsRequired()
                        .HasConstraintName("posts_authorid_fkey");

                    b.Navigation("Artist");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Disco.Models.PostReaction", b =>
                {
                    b.HasOne("Disco.Models.Post", "Post")
                        .WithMany("PostReactions")
                        .HasForeignKey("Postid")
                        .IsRequired()
                        .HasConstraintName("post_reactions_postid_fkey");

                    b.HasOne("Disco.Models.User", "User")
                        .WithMany("PostReactions")
                        .HasForeignKey("Userid")
                        .IsRequired()
                        .HasConstraintName("post_reactions_userid_fkey");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Disco.Models.RepliesReaction", b =>
                {
                    b.HasOne("Disco.Models.Reply", "Reply")
                        .WithMany("RepliesReactions")
                        .HasForeignKey("Replyid")
                        .IsRequired()
                        .HasConstraintName("replies_reactions_replyid_fkey");

                    b.HasOne("Disco.Models.User", "User")
                        .WithMany("RepliesReactions")
                        .HasForeignKey("Userid")
                        .IsRequired()
                        .HasConstraintName("replies_reactions_userid_fkey");

                    b.Navigation("Reply");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Disco.Models.Reply", b =>
                {
                    b.HasOne("Disco.Models.User", "Author")
                        .WithMany("Replies")
                        .HasForeignKey("Authorid")
                        .IsRequired()
                        .HasConstraintName("replies_authorid_fkey");

                    b.HasOne("Disco.Models.Reply", "Parent")
                        .WithMany("InverseParent")
                        .HasForeignKey("Parentid")
                        .HasConstraintName("replies_parentid_fkey");

                    b.HasOne("Disco.Models.Post", "Post")
                        .WithMany("Replies")
                        .HasForeignKey("Postid")
                        .IsRequired()
                        .HasConstraintName("replies_postid_fkey");

                    b.Navigation("Author");

                    b.Navigation("Parent");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("UsersFollower", b =>
                {
                    b.HasOne("Disco.Models.User", null)
                        .WithMany()
                        .HasForeignKey("Followedid")
                        .IsRequired()
                        .HasConstraintName("users_followers_followedid_fkey");

                    b.HasOne("Disco.Models.User", null)
                        .WithMany()
                        .HasForeignKey("Followerid")
                        .IsRequired()
                        .HasConstraintName("users_followers_followerid_fkey");
                });

            modelBuilder.Entity("Disco.Models.Artist", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("Disco.Models.Post", b =>
                {
                    b.Navigation("PostReactions");

                    b.Navigation("Replies");
                });

            modelBuilder.Entity("Disco.Models.Reply", b =>
                {
                    b.Navigation("InverseParent");

                    b.Navigation("RepliesReactions");
                });

            modelBuilder.Entity("Disco.Models.User", b =>
                {
                    b.Navigation("PostReactions");

                    b.Navigation("Posts");

                    b.Navigation("Replies");

                    b.Navigation("RepliesReactions");
                });
#pragma warning restore 612, 618
        }
    }
}
